//! Build script for `oxideav-musepack`.
//!
//! Reads the CSV-shaped numeric tables under
//! `docs/audio/musepack/tables/` (relative to the workspace root) and
//! emits typed Rust constant arrays into `OUT_DIR` so the crate can
//! `include!` them at compile time. Only the *numeric initialisers*
//! are crossed; no implementation source is read or referenced. The
//! CSVs and `.meta` sidecars are themselves the Feist-style facts
//! produced by the walled extraction round documented at
//! `docs/audio/musepack/provenance/01-musepack-table-extraction.md`.
//!
//! Generated files:
//!
//! - `sv7_huffman_tables.rs` — one `pub static` array of
//!   `crate::huffman::Sv7Entry` per `sv7-huffman-*.csv` plus a
//!   helper accessor for the `[2][N]` context-pair tables.
//! - `cns_prng_tables.rs` — the 256-byte `PARITY` table and the
//!   scalar PRNG parameters from `cns-prng-{parity,params}.csv`.
//!
//! Each generator splits the `[2][N]` SV7 quantiser CSVs at
//! `element_count / 2` per the staged sidecars' `notes:` line.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Source-of-truth for the CSVs is the staged docs collaborator's
    // `docs/audio/musepack/tables/` directory. Because the crate
    // publishes / CIs standalone (no docs submodule on the runner),
    // a *vendored snapshot* of the exact subset consumed here also
    // lives under `<manifest>/tables/`. The build script picks the
    // first available source from this priority list:
    //
    //   1. `OXIDEAV_MUSEPACK_DOCS_DIR/audio/musepack/tables/` —
    //      explicit env-var override (used by sandboxed builds that
    //      want to point at an arbitrary docs checkout).
    //   2. `<workspace-root>/docs/audio/musepack/tables/` — the live
    //      docs submodule, when the crate is built from inside the
    //      umbrella workspace.
    //   3. `<manifest>/tables/` — the vendored snapshot; this is
    //      what CI / crates.io consumers see.
    //
    // The snapshot under `<manifest>/tables/` must stay byte-equal
    // with the umbrella's `docs/audio/musepack/tables/`; refreshing
    // it is a manual step when the docs collaborator restages.
    let manifest_dir = PathBuf::from(env_var("CARGO_MANIFEST_DIR"));
    let env_override = std::env::var("OXIDEAV_MUSEPACK_DOCS_DIR")
        .ok()
        .map(|s| PathBuf::from(s).join("audio/musepack/tables"));
    let workspace_docs = manifest_dir
        .parent()
        .and_then(Path::parent)
        .map(|root| root.join("docs/audio/musepack/tables"));
    let vendored = manifest_dir.join("tables");

    let tables_dir = [
        env_override.as_ref(),
        workspace_docs.as_ref(),
        Some(&vendored),
    ]
    .into_iter()
    .flatten()
    .find(|p| p.is_dir())
    .cloned()
    .expect(
        "no Musepack tables directory found: tried \
             $OXIDEAV_MUSEPACK_DOCS_DIR, <workspace>/docs/audio/musepack/tables/, \
             and <crate>/tables/ — none exist",
    );
    println!("cargo:rerun-if-env-changed=OXIDEAV_MUSEPACK_DOCS_DIR");

    let out_dir = PathBuf::from(env_var("OUT_DIR"));

    emit_sv7_huffman_tables(&tables_dir, &out_dir);
    emit_cns_prng_tables(&tables_dir, &out_dir);
    emit_sv8_canonical_tables(&tables_dir, &out_dir);

    // Re-run if any input changes.
    println!("cargo:rerun-if-changed=build.rs");
    for entry in fs::read_dir(&tables_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if matches!(path.extension().and_then(|s| s.to_str()), Some("csv")) {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn env_var(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("env var {name} must be set by cargo"))
}

// ─── SV7 mpc_huffman tables ─────────────────────────────────────

/// All SV7 mpc_huffman CSVs we emit. The entries that the `.meta`
/// `raw_dims` line records as `[2][N]` are flagged here so the
/// generator can also emit a per-context slice accessor.
const SV7_HUFFMAN_INPUTS: &[(&str, &str, bool)] = &[
    // (stem, RUST_IDENT_PREFIX, is_context_pair)
    ("sv7-huffman-bandtype-header", "SV7_BANDTYPE_HEADER", false),
    ("sv7-huffman-scfi", "SV7_SCFI", false),
    ("sv7-huffman-dscf", "SV7_DSCF", false),
    ("sv7-huffman-q1", "SV7_Q1", true),
    ("sv7-huffman-q2", "SV7_Q2", true),
    ("sv7-huffman-q3", "SV7_Q3", true),
    ("sv7-huffman-q4", "SV7_Q4", true),
    ("sv7-huffman-q5", "SV7_Q5", true),
    ("sv7-huffman-q6", "SV7_Q6", true),
    ("sv7-huffman-q7", "SV7_Q7", true),
];

fn emit_sv7_huffman_tables(tables_dir: &Path, out_dir: &Path) {
    let mut out = String::new();
    out.push_str(
        "// Auto-generated by build.rs from docs/audio/musepack/tables/.\n\
         // Source of truth: the *.csv files at the path above. DO NOT EDIT\n\
         // this file directly; edit the staged CSV (or build.rs) instead.\n\n",
    );

    for (stem, ident, is_pair) in SV7_HUFFMAN_INPUTS {
        let csv_path = tables_dir.join(format!("{stem}.csv"));
        let rows = parse_sv7_huffman_csv(&csv_path);
        emit_sv7_huffman_array(&mut out, ident, &rows, *is_pair, stem);
    }

    fs::write(out_dir.join("sv7_huffman_tables.rs"), out)
        .expect("write OUT_DIR/sv7_huffman_tables.rs");
}

fn parse_sv7_huffman_csv(path: &Path) -> Vec<(u16, u8, i8)> {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut rows = Vec::new();
    for (i, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut cols = line.split(',');
        let code_s = cols.next().unwrap_or("");
        let len_s = cols.next().unwrap_or("");
        let val_s = cols.next().unwrap_or("");
        let code_hex = code_s
            .strip_prefix("0x")
            .or_else(|| code_s.strip_prefix("0X"))
            .unwrap_or_else(|| {
                panic!(
                    "{}:{}: expected 0x-prefixed code, got {code_s:?}",
                    path.display(),
                    i + 1
                )
            });
        let code = u16::from_str_radix(code_hex, 16)
            .unwrap_or_else(|e| panic!("{}:{}: parse code {code_s:?}: {e}", path.display(), i + 1));
        let length: u8 = len_s.parse().unwrap_or_else(|e| {
            panic!("{}:{}: parse length {len_s:?}: {e}", path.display(), i + 1)
        });
        let value: i8 = val_s
            .parse()
            .unwrap_or_else(|e| panic!("{}:{}: parse value {val_s:?}: {e}", path.display(), i + 1));
        rows.push((code, length, value));
    }
    rows
}

fn emit_sv7_huffman_array(
    out: &mut String,
    ident_prefix: &str,
    rows: &[(u16, u8, i8)],
    is_pair: bool,
    stem: &str,
) {
    let len = rows.len();
    out.push_str(&format!(
        "/// SV7 Huffman table generated from `docs/audio/musepack/tables/{stem}.csv`.\n\
         ///\n\
         /// Layout per the `.meta` sidecar: `mpc_huffman = {{Code:uint16 left-adjusted,\n\
         /// Length:uint8, Value:int8}}`, sorted by `Code` descending.\n\
         pub static {ident_prefix}_TABLE: [crate::huffman::Sv7Entry; {len}] = [\n"
    ));
    for (code, length, value) in rows {
        out.push_str(&format!(
            "    crate::huffman::Sv7Entry {{ code: {code:#06x}, length: {length}, value: {value} }},\n"
        ));
    }
    out.push_str("];\n\n");

    if is_pair {
        assert!(
            len % 2 == 0,
            "context-pair table {stem} has odd length {len}"
        );
        let half = len / 2;
        out.push_str(&format!(
            "/// Per-context slice into [`{ident}_TABLE`]. `ctx` is the first-order\n\
             /// context selector (0 or 1) per the `.meta` notes line.\n\
             pub fn {fn_name}(ctx: usize) -> &'static [crate::huffman::Sv7Entry] {{\n\
             \x20   match ctx {{\n\
             \x20       0 => &{ident}_TABLE[0..{half}],\n\
             \x20       1 => &{ident}_TABLE[{half}..{len}],\n\
             \x20       _ => panic!(\"{fn_name}: context {{ctx}} out of 0..=1\"),\n\
             \x20   }}\n\
             }}\n\n",
            ident = ident_prefix,
            fn_name = format!("{}_ctx", ident_prefix.to_lowercase()),
        ));
    }
}

// ─── CNS PRNG tables ────────────────────────────────────────────

fn emit_cns_prng_tables(tables_dir: &Path, out_dir: &Path) {
    let mut out = String::new();
    out.push_str(
        "// Auto-generated by build.rs from docs/audio/musepack/tables/cns-prng-*.csv.\n\n",
    );

    // Parity table: 256 rows, each row a single `0` or `1` byte.
    let parity_path = tables_dir.join("cns-prng-parity.csv");
    let parity_text = fs::read_to_string(&parity_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", parity_path.display()));
    let parity: Vec<u8> = parity_text
        .lines()
        .filter_map(|l| {
            let t = l.trim();
            if t.is_empty() || t.starts_with('#') {
                None
            } else {
                Some(t.parse::<u8>().unwrap_or_else(|e| {
                    panic!("{}: parse parity bit {t:?}: {e}", parity_path.display())
                }))
            }
        })
        .collect();
    assert_eq!(
        parity.len(),
        256,
        "cns-prng-parity.csv must have 256 rows, got {}",
        parity.len()
    );
    for (i, bit) in parity.iter().enumerate() {
        assert!(*bit <= 1, "parity row {i} is not 0/1");
    }
    out.push_str(
        "/// 256-entry byte-parity lookup used by the CNS / noise-substitution\n\
         /// PRNG. Index by a `u8`; `PARITY[b] == 1` iff the popcount of `b`\n\
         /// is odd.\n\
         pub static PARITY: [u8; 256] = [\n",
    );
    for chunk in parity.chunks(16) {
        out.push_str("    ");
        for b in chunk {
            out.push_str(&format!("{b}, "));
        }
        out.push('\n');
    }
    out.push_str("];\n\n");

    // Scalar params CSV: each row `name,value`. Value is decimal except
    // the two `*_tap_mask` rows which are hex.
    let params_path = tables_dir.join("cns-prng-params.csv");
    let params_text = fs::read_to_string(&params_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", params_path.display()));
    let mut params: std::collections::BTreeMap<String, String> = std::collections::BTreeMap::new();
    for (i, line) in params_text.lines().enumerate() {
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') {
            continue;
        }
        let mut cols = t.splitn(2, ',');
        let name = cols.next().unwrap_or("").trim().to_string();
        let value = cols.next().unwrap_or("").trim().to_string();
        if name.is_empty() {
            panic!("{}:{}: blank parameter name", params_path.display(), i + 1);
        }
        params.insert(name, value);
    }

    let r1_seed = parse_decimal_u32(params.get("r1_seed").expect("r1_seed"), "r1_seed");
    let r2_seed = parse_decimal_u32(params.get("r2_seed").expect("r2_seed"), "r2_seed");
    let r1_tap_mask = parse_hex_u32(
        params.get("r1_tap_mask").expect("r1_tap_mask"),
        "r1_tap_mask",
    );
    let r2_tap_mask = parse_hex_u32(
        params.get("r2_tap_mask").expect("r2_tap_mask"),
        "r2_tap_mask",
    );
    let r2_shift = parse_decimal_u32(params.get("r2_shift").expect("r2_shift"), "r2_shift");
    let bias_str = params
        .get("noise_sample_byte_sum_bias")
        .expect("noise_sample_byte_sum_bias");
    let bias: i32 = bias_str
        .parse()
        .unwrap_or_else(|e| panic!("noise_sample_byte_sum_bias parse {bias_str:?}: {e}"));

    out.push_str(&format!(
        "/// Initial value loaded into the right-rotating LFSR (`r1`).\n\
         pub const R1_SEED: u32 = {r1_seed};\n\n\
         /// Initial value loaded into the left-rotating LFSR (`r2`).\n\
         pub const R2_SEED: u32 = {r2_seed};\n\n\
         /// Tap mask for `r1` (looked up via [`PARITY`] of `r1 & R1_TAP_MASK`).\n\
         pub const R1_TAP_MASK: u32 = {r1_tap_mask:#x};\n\n\
         /// Tap mask for `r2` (looked up via [`PARITY`] of `(r2 >> R2_SHIFT) & R2_TAP_MASK`).\n\
         pub const R2_TAP_MASK: u32 = {r2_tap_mask:#x};\n\n\
         /// Right-shift amount applied to `r2` before tap-masking.\n\
         pub const R2_SHIFT: u32 = {r2_shift};\n\n\
         /// Bias subtracted from the unsigned byte-sum of one 32-bit PRNG\n\
         /// word to produce the signed noise sample `q[k]` in range\n\
         /// `-510..=510`.\n\
         pub const NOISE_SAMPLE_BYTE_SUM_BIAS: i32 = {bias};\n",
    ));

    fs::write(out_dir.join("cns_prng_tables.rs"), out).expect("write OUT_DIR/cns_prng_tables.rs");
}

fn parse_decimal_u32(s: &str, name: &str) -> u32 {
    s.parse()
        .unwrap_or_else(|e| panic!("cns-prng-params {name}={s:?}: {e}"))
}

fn parse_hex_u32(s: &str, name: &str) -> u32 {
    let body = s
        .strip_prefix("0x")
        .or_else(|| s.strip_prefix("0X"))
        .unwrap_or_else(|| panic!("cns-prng-params {name}={s:?}: expected 0x-prefixed hex"));
    u32::from_str_radix(body, 16)
        .unwrap_or_else(|e| panic!("cns-prng-params {name}={s:?}: parse hex: {e}"))
}

// ─── SV8 canonical Huffman tables ───────────────────────────────

/// Catalogue of all SV8 canonical-length tables + their paired
/// symbol maps. Each entry pairs a `sv8-canonical-<stem>.csv` file
/// with its `sv8-symbols-<stem>.csv` partner.
///
/// The stems are recorded in `docs/audio/musepack/musepack-sv7-sv8-spec.md`
/// §4 ("SV8 canonical Huffman codebooks") and in
/// `docs/audio/musepack/provenance/01-musepack-table-extraction.md`
/// §6 ("SV8 canonical length-tables + symbol maps"). The 21
/// catalogue entries match the 21 length-table / 21 symbol-map pair
/// inventory recorded there.
const SV8_CANONICAL_INPUTS: &[(&str, &str)] = &[
    // (stem, RUST_IDENT_PREFIX)
    ("bands", "SV8_BANDS"),
    ("res-1", "SV8_RES_1"),
    ("res-2", "SV8_RES_2"),
    ("scfi-1", "SV8_SCFI_1"),
    ("scfi-2", "SV8_SCFI_2"),
    ("dscf-1", "SV8_DSCF_1"),
    ("dscf-2", "SV8_DSCF_2"),
    ("q1", "SV8_Q1"),
    ("q2-1", "SV8_Q2_1"),
    ("q2-2", "SV8_Q2_2"),
    ("q3", "SV8_Q3"),
    ("q4", "SV8_Q4"),
    ("q5-1", "SV8_Q5_1"),
    ("q5-2", "SV8_Q5_2"),
    ("q6-1", "SV8_Q6_1"),
    ("q6-2", "SV8_Q6_2"),
    ("q7-1", "SV8_Q7_1"),
    ("q7-2", "SV8_Q7_2"),
    ("q8-1", "SV8_Q8_1"),
    ("q8-2", "SV8_Q8_2"),
    ("q9up", "SV8_Q9UP"),
];

fn emit_sv8_canonical_tables(tables_dir: &Path, out_dir: &Path) {
    let mut out = String::new();
    out.push_str(
        "// Auto-generated by build.rs from docs/audio/musepack/tables/sv8-canonical-* \n\
         // and sv8-symbols-*.\n\
         //\n\
         // Each canonical length-table row is (code_left_adjusted_hex,\n\
         // length_bits, cumulative_index). The paired symbol map is an\n\
         // int8 array indexed by the cumulative-index walk the decoder\n\
         // performs against the length-table. DO NOT EDIT — edit the\n\
         // staged CSV (or build.rs) instead.\n\n",
    );

    for (stem, ident) in SV8_CANONICAL_INPUTS {
        let canon_path = tables_dir.join(format!("sv8-canonical-{stem}.csv"));
        let sym_path = tables_dir.join(format!("sv8-symbols-{stem}.csv"));
        let rows = parse_sv8_canonical_csv(&canon_path);
        let syms = parse_sv8_symbols_csv(&sym_path);
        emit_sv8_canonical_arrays(&mut out, ident, stem, &rows, &syms);
    }

    fs::write(out_dir.join("sv8_canonical_tables.rs"), out)
        .expect("write OUT_DIR/sv8_canonical_tables.rs");
}

/// Parse one `sv8-canonical-*.csv`. Each row is
/// `code_left_adjusted_hex,length_bits,cumulative_index`. The
/// cumulative-index column is signed in some tables (the `q9up`
/// large-coefficient-escape map has signed indices), so we parse it
/// as `i16` and let the decoder reinterpret.
fn parse_sv8_canonical_csv(path: &Path) -> Vec<(u16, u8, i16)> {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut rows = Vec::new();
    for (i, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut cols = line.split(',');
        let code_s = cols.next().unwrap_or("");
        let len_s = cols.next().unwrap_or("");
        let cum_s = cols.next().unwrap_or("");
        let code_hex = code_s
            .strip_prefix("0x")
            .or_else(|| code_s.strip_prefix("0X"))
            .unwrap_or_else(|| {
                panic!(
                    "{}:{}: expected 0x-prefixed code, got {code_s:?}",
                    path.display(),
                    i + 1
                )
            });
        let code = u16::from_str_radix(code_hex, 16)
            .unwrap_or_else(|e| panic!("{}:{}: parse code {code_s:?}: {e}", path.display(), i + 1));
        let length: u8 = len_s.parse().unwrap_or_else(|e| {
            panic!("{}:{}: parse length {len_s:?}: {e}", path.display(), i + 1)
        });
        let cum: i16 = cum_s
            .parse()
            .unwrap_or_else(|e| panic!("{}:{}: parse cum {cum_s:?}: {e}", path.display(), i + 1));
        rows.push((code, length, cum));
    }
    rows
}

/// Parse one `sv8-symbols-*.csv`. Each row is a single signed-8-bit
/// integer (`int8` in the source `mpc_sym_*` arrays).
fn parse_sv8_symbols_csv(path: &Path) -> Vec<i8> {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut syms = Vec::new();
    for (i, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let value: i8 = line
            .parse()
            .unwrap_or_else(|e| panic!("{}:{}: parse symbol {line:?}: {e}", path.display(), i + 1));
        syms.push(value);
    }
    syms
}

fn emit_sv8_canonical_arrays(
    out: &mut String,
    ident_prefix: &str,
    stem: &str,
    rows: &[(u16, u8, i16)],
    syms: &[i8],
) {
    let rlen = rows.len();
    out.push_str(&format!(
        "/// SV8 canonical Huffman **length table** generated from\n\
         /// `docs/audio/musepack/tables/sv8-canonical-{stem}.csv`.\n\
         ///\n\
         /// Each row is `(Code, Length, CumIdx)` per the `.meta`\n\
         /// `mpc_huffman = {{Code:uint16 left-adjusted, Length:uint8,\n\
         /// Value:cumulative index into the paired symbol map}}`\n\
         /// convention. The decoder convention (how peek →\n\
         /// (sub_off, symbol_index) within a length class) is\n\
         /// **DOCS-GAP** — the structural prose names the shape and\n\
         /// pairs the tables, but does not pin the cumulative-index\n\
         /// walk arithmetic. Downstream decoder rounds depend on a\n\
         /// docs-collaborator §3.4 patch resolving the walk.\n\
         pub static {ident_prefix}_LEN_TABLE: [crate::sv8_huffman::Sv8CanonicalEntry; {rlen}] = [\n"
    ));
    for (code, length, cum) in rows {
        out.push_str(&format!(
            "    crate::sv8_huffman::Sv8CanonicalEntry {{ code: {code:#06x}, length: {length}, cum_index: {cum} }},\n"
        ));
    }
    out.push_str("];\n\n");

    let slen = syms.len();
    out.push_str(&format!(
        "/// SV8 canonical Huffman **symbol map** paired with\n\
         /// [`{ident_prefix}_LEN_TABLE`]. Generated from\n\
         /// `docs/audio/musepack/tables/sv8-symbols-{stem}.csv`.\n\
         pub static {ident_prefix}_SYM_TABLE: [i8; {slen}] = [\n"
    ));
    for chunk in syms.chunks(16) {
        out.push_str("    ");
        for s in chunk {
            out.push_str(&format!("{s}, "));
        }
        out.push('\n');
    }
    out.push_str("];\n\n");

    // Paired-table accessor returning the canonical pair as one
    // [`Sv8CanonicalTable`] view (length-table slice + symbol-map
    // slice).
    out.push_str(&format!(
        "/// Paired (length-table, symbol-map) view of the\n\
         /// `sv8-canonical-{stem}` + `sv8-symbols-{stem}` table pair.\n\
         pub static {ident_prefix}_TABLE: crate::sv8_huffman::Sv8CanonicalTable =\n\
         \x20   crate::sv8_huffman::Sv8CanonicalTable {{\n\
         \x20       lengths: &{ident_prefix}_LEN_TABLE,\n\
         \x20       symbols: &{ident_prefix}_SYM_TABLE,\n\
         \x20       name: \"sv8-canonical-{stem}\",\n\
         \x20   }};\n\n",
    ));
}
